function combineall = importfile1(filename, dataLines)
%IMPORTFILE1 Import data from a text file
%  COMBINEALL = IMPORTFILE1(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the data as a table.
%
%  COMBINEALL = IMPORTFILE1(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  combineall = importfile1("/Users/yousefqadumi/Documents/GitHub/KINE6203Submissions/combine_all.csv", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 02-Oct-2024 13:08:36

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 19);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["year", "position", "heightfeet", "heightinches", "heightinchestotal", "weight", "arms", "hands", "fortyyd", "twentyyd", "tenyd", "twentyss", "threecone", "vertical", "broad", "bench", "nflgrade", "college", "roundDrafted"];
opts.VariableTypes = ["double", "categorical", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "string", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "college", "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["position", "college"], "EmptyFieldRule", "auto");

% Import the data
combineall = readtable(filename, opts);

end